### ISSUE TITLE
Makefile with Cygwin

### ISSUE THREAD

**Issue by TerenceSperringerJr** [PublicHealthDynamicsLab/FRED#46]
The following error occurred when running `make`:

```
make[1]: Entering directory '/cygdrive/c/Users/.../FRED/doc'
rst2pdf FRED_UserGuide.rst -o FRED_UserGuide.pdf --repeat-table-rows -s FRED.css
Traceback (most recent call last):
  File "c:\users\...\appdata\local\continuum\anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\...\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\AppData\Local\Continuum\Anaconda3\Scripts\rst2pdf.exe\__main__.py", line 5, in <module>
  File "c:\users\...\appdata\local\continuum\anaconda3\lib\site-packages\rst2pdf\createpdf.py", line 695
    except ValueError, v:
                     ^
SyntaxError: invalid syntax
make[1]: *** [Makefile:10: FRED_UserGuide.pdf] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/.../FRED/doc'
input_files
```

Except for above, the build continued without error.

**Comment by TerenceSperringerJr** [comment]
This looks like it's just an error in generating documentation, but would this affect the way FRED runs?

**Comment by gallowdd** [comment]
Not at all
